### ISSUE TITLE
Bring port up to date with Java version

### ISSUE THREAD

**Issue by JPWatson** [AdaptiveConsulting/Aeron.NET#39]
Port changes from https://github.com/real-logic/Aeron/commit/a15baaafe7b3da686772b95238425c45d1fb5909 to https://github.com/real-logic/Aeron/commit/fbefcadbea39424e15a550e3d99acedd9dd9fa5a

**Comment by JPWatson** [comment]
- [ ] a15baaa [Java] Remove hangover printStackTrace from closing UdpChannelTransports.
- [ ] d9aea57 [Java] Pull out receive buffers and flyweights from channel endpoints to transport pollers so that buffers can be reused to reduce memory footprint and cache misses.
- [ ] cc940be [Java] No need to initial channel status as counter will be zero by default.
- [ ] d9551d8 [Java] Allocated SM and NAK buffer and flyweights as static in ReceiveChannelEndpoint to save on memory usages, cache misses, and connection setup time.
- [ ] 796fb9a [Java] Consolidate the four short send counters into a single counter.
- [ ] 5a1f31e [Java] Use thread local buffers so multiple media drivers can be embedded in the same process.
- [ ] 6bb00ba [Java] Pull out NetworkPublication SM and HEARTBEAT buffers and flyweights into thread locals for reuse to save memory and cache misses for high numbers of connections.
- [ ] 1fec4e9 [Java] Save lookup of initialTermId in DirectPublication when computing producer position.
- [ ] e134f2d [Java] Change samples to use aligned publication buffers.
- [ ] 5881753 [Java] Increase number of messages for ping scripts.
- [ ] 25d3067 [Java]: use thread local with initial
- [ ] 2449c8b [Java] Place threadLocals for NetworkPublication in the DriverConductor.
- [ ] 50eb2d9 [Java] Place threadLocals for ReceiveChannelEndpoint in the Context.
- [ ] 1039504 [Java] Remove unnecessary space from label.
- [ ] 8185b32 [Java] Simplify naming.
- [ ] ba1a6d9 [Java] Remove duplicate zeroing of counter.
- [ ] f83754c [Java] Don't use sparse files in low latency usecases.
- [ ] fd35d37 [Java] Added embedded-ipc-throughput.bat
- [ ] 457678d [Java]  Added embedded-ipc-throughput bash script.
- [ ] d56e1af [Java] Separate termOffset and termId from the packed rawTail in the meta data for log inspection.
- [ ] f0a223d [Java] Don't need to truncate termOffset to an int when outputting and full value can be useful for inspection.
- [ ] 2609a6e 0.9.8 released
- [ ] 51fde65 post release bump
- [ ] 365ff51 [Java] Change filePoll on Subscription to be rawPoll that passes the term buffer as well as the file channel for full access to the block for archiving are other purposes that require full raw access.
- [ ] e05a0bc [Java] Set the reserved value on the DataHeaderFlyweight with a long rather than int argument.
- [ ] 2f7214a [Java] Static import.
- [ ] 71a965b [Java] Validate MTU length is a multiple of frame alignment.
- [ ] ceb3942 [Java] Validate MTU length with a mod operation rather than mask in case it is not a power of 2.
- [ ] f16deef [C++]: Retarget to CMake version 3.0.2
- [ ] e508f06 [C++]: Switch to CMake project version parsed from version.txt
- [ ] 116ed9d Merge pull request #231 from vdidenko/project_version_in_cmake
- [ ] 9918c9f [Java] Added the ability to specify the term buffer length when adding a publication via a channel uri parameter. Issue #193.
- [ ] 73f3fa9 [Java] StoreStore fence after writing a  zero to the length when rebuilding the log buffer on the receiver side.
- [ ] 0b2c929 [Java]: #234 reduce receiver window to min of term length / 2 and static setting.
- [ ] 1958328 [Java] Change a number of tests to use the aeron: uri channel syntax.
- [ ] 958e784 [Java] Change UdpChannelTest to use the aeron: uri channel syntax and issue a deprecation warning for old format.
- [ ] bd1a9fd [Java] Capture error output in test and assert on it.
- [ ] 58a8743 [Java]: add initial internal support for Spy semantics.
- [ ] 8d9491a [Java] Minor tidy up during review.
- [ ] a2522b5 [Java] Migrate the remaining examples of the old channel format to the new aeron:udp channel format.
- [ ] d7727cc [Java]: fixed #235 by checking for resolution status before accessing endpoint address and throwing more informative exception.
- [ ] d3e5144 [Java]: added unit tests for spy semantics #230
- [ ] 170f8b2 [Java]: added #235 with system tests for spy subscription semantics.
- [ ] 66a0fed [Java]: added #230 with system tests for spy subscription semantics.
- [ ] 4a622cc Merge branch 'master' of https://github.com/real-logic/Aeron
- [ ] 94070a3 [Java]  Added embedded-throughput bash script.
- [ ] 3922c82 [Java] Added embedded-throughput.bat Windows batch script.
- [ ] ac6f9fd [Java] Formatting.
- [ ] 1cea414 [Java] Added an overload option to Publication.offer() to allow for a ReservedValueSupplier. This can be useful for adding timestamps or other meta data to the reserved value field in the header.
- [ ] aa2666d [Java] Argument naming.
- [ ] b3f4d0c [C++]: add reserved value supplier for Publication::offer.
- [ ] d3aa1a6 [C++]: add functional include
- [ ] 734c692 [Java] Code styling.
- [ ] 8405053 [Java] Factor out code to get term length as a channel param.
- [ ] eb11d4c [Java] Validate max MTU length for UDP payloads.
- [ ] 7690471 [Java] Allow for IPC having a different default term buffer length.
- [ ] fbefcad [Java] Naming.
