### ISSUE TITLE
Update to v1.0

### ISSUE THREAD

**Issue by JPWatson** [AdaptiveConsulting/Aeron.NET#46]
Aeron
====
- [x] 88e974e [Java] Apply mapMode for largest size term buffers.
- [x] e8051ac [Java] Link to .NET repo and update CMAKE requirements.
- [x] 7483adc [Java] typo.
- [x] 79b428d [Java] Add Javadoc to defaults in Aeron client.
- [x] 4f236b0 [Java] Add the ability to set the driver error handler in the context.
- [x] 6a84957 [Java] Group related properties and improve javadoc.
- [x] 660c0a6 [Java] Whitespace.
- [x] 0755f13 [Java] Further reorg of configuration properties.
- [x] 3fae39e [Java] Further tidy up and javadoc for configuration.
- [x] 8fabdbe [Java] Javadoc.
- [x] 6a7c97b [Java] Javadoc.
- [x] b7cd7ca [Java] Naming and increase size of event buffer to 2MB.
- [x] afdb130 [Java] Javadoc.
- [x] d7ee8be [Java] Update to ByteBuddy 1.4.6.
- [x] 74b49f9 [Java] Limit scope of constants.
- [x] db0aa9b [Java] Javadoc.
- [x] f2182f5 [Java] On reflection the data frame header can be done with normal writes in any order given how the unblocker now works.
- [x] 0516a57 [Java] Revert last change.
- [x] 92b1acc [Java] Remove unused status field accessors.
- [x] fcc5ff0 [cpp] Removed unused method.
- [x] fae5d09 [Java] Depend on Agrona snapshot.
- [x] 948d8b2 [Java] Correct typo and use CommonContext.SPY_PREFIX.
- [x] 8d84f75 [Java] Busy spin the conductor for low latency.
- [x] c2d7efd [Java] Only run client conductor duty cycle one every 10ms.
- [x] 47c9b11 [Java] What for driver to initialise the CnC file. Issue #251.
- [x] 1e1c1c3 [Java] Wait on CnC file to exist for allowing client to start before the driver. Issue #251.
- [x] 96dcb0d [Java] Javadoc.
- [x] afa4899 [Java] Javadoc.
- [x] a93ca0e [Java] Writing the length field can be a normal put long provided it is followed by a store fence for the first write of the header fields.
- [x] 14f2411 [C++]:  Disable bounds checks for release builds of media driver.
- [x] 4e014cf [C++]: add thread_fence() after volatile write of negative frame length.
- [x] 714113a [Java] Use arrays rather than ArrayLists for positions in publications and images in the driver.
- [x] 41a18e1 Merge remote-tracking branch 'origin/master'
- [x] 0879627 [Java] Upgrade to ByteBuddy 1.4.7.
- [x] 875f7bb [Java] Upgrade to ByteBuddy 1.4.8.
- [x] 3733f6c [Java] Move tail counters into log meta data for the Publication which allows for simplification of the log structure and reduce data dependant loads throughout Aeron.
- [x] 99ebefd [Java] Place the active partition index in the same cache line as the tail counters within the log.
- [x] f704681 [C++]: reflect tail counters being moved into log meta data buffer.
- [x] 18ec519 [C++]: add spins on CnC file to Aeron constructor.
- [x] c54f276 [Java] Javadoc correction.
- [x] dee27a0 Merge remote-tracking branch 'origin/master'
- [x] b8d83be [Java] Give up the thread on an setup thread which is adding publications or subscriptions to that CPU resource is available to other threads to complete the action. Issue #244.
- [x] 8815092 [Java] Naming.
- [x] 3352811 [Java] Incremental cleaning of log buffers by the conductor to smooth out pauses in the driver conductor.
- [x] 5800f5f [Java] Lag the cleaning by a term + window to allow for greater NAK range.
- [x] b7a0be3 [Java] Naming of cleaning variables for clarity.
- [x] b882e71 [Java] Check resend of a NAK is within one term length behind the sender position. Also clean incrementally from 2 term lengths behind publication limit for the NetworkPublication. Issue #257.
- [x] 21c27b0 [Java] Naming.
- [x] 3d060f1 [Java] Naming.
- [x] d6eec29 [Java] README.
- [x] 32504cb [Java] README.
- [x] 6f2d1f1 [Java]: avoid issuing availableImage on addSubscription when existing image status isn't ACTIVE.
- [x] bbaf75d [Java]: switch filtering of addImage for availableImage to be correlationId based instead of sessionId.
- [x] bb6f682 [C++]: make hasImage be correlationId based.
- [x] 6d3d702 [Java] naming.
- [x] 34d53ea Merge branch 'master' of https://github.com/real-logic/Aeron
- [x] 023d9e2 [Java] Use concrete typed position counters in status package.
- [x] 80c5710 [C++] Added setting clientId on remove messages to the driver
- [x] f07738b [Java] Simplify DriverProxy as it is only called on the conductor lock and benefit from the clientId field set in the buffer.
- [x] 2808ab8 [Java] Simplify DriverProxy as it is only called under the client conductor lock and benefit from the clientId field set in the buffer.
- [x] d1a76af Merge pull request #259 from lirm/master
- [x] 27ade16 [Java] Styling.
- [x] 677399a [Java] Upgrade to ByteBuddy 1.4.9.
- [x] 957e552 [Java] Upgrade to Checkstyle 7.0.
- [x] d31a838 [Java] Styling.
- [x] 375b625 [Java] Exposed max payload length from a publication.
- [x] c2e5378 [C++]: add maxPayloadLength to Publication
- [x] 7b21578 1.0 released

**Comment by JPWatson** [comment]
- [ ] 88e974e [Java] Apply mapMode for largest size term buffers.
- [ ] e8051ac [Java] Link to .NET repo and update CMAKE requirements.
- [ ] 7483adc [Java] typo.
- [ ] 79b428d [Java] Add Javadoc to defaults in Aeron client.
- [ ] 4f236b0 [Java] Add the ability to set the driver error handler in the context.
- [ ] 6a84957 [Java] Group related properties and improve javadoc.
- [ ] 660c0a6 [Java] Whitespace.
- [ ] 0755f13 [Java] Further reorg of configuration properties.
- [ ] 3fae39e [Java] Further tidy up and javadoc for configuration.
- [ ] 8fabdbe [Java] Javadoc.
- [ ] 6a7c97b [Java] Javadoc.
- [ ] b7cd7ca [Java] Naming and increase size of event buffer to 2MB.
- [ ] afdb130 [Java] Javadoc.
- [ ] d7ee8be [Java] Update to ByteBuddy 1.4.6.
- [ ] 74b49f9 [Java] Limit scope of constants.
- [ ] db0aa9b [Java] Javadoc.
- [ ] f2182f5 [Java] On reflection the data frame header can be done with normal writes in any order given how the unblocker now works.
- [ ] 0516a57 [Java] Revert last change.
- [ ] 92b1acc [Java] Remove unused status field accessors.
- [ ] fcc5ff0 [cpp] Removed unused method.
- [ ] fae5d09 [Java] Depend on Agrona snapshot.
- [ ] 948d8b2 [Java] Correct typo and use CommonContext.SPY_PREFIX.
- [ ] 8d84f75 [Java] Busy spin the conductor for low latency.
- [ ] c2d7efd [Java] Only run client conductor duty cycle one every 10ms.
- [ ] 47c9b11 [Java] What for driver to initialise the CnC file. Issue #251.
- [ ] 1e1c1c3 [Java] Wait on CnC file to exist for allowing client to start before the driver. Issue #251.
- [ ] 96dcb0d [Java] Javadoc.
- [ ] afa4899 [Java] Javadoc.
- [ ] a93ca0e [Java] Writing the length field can be a normal put long provided it is followed by a store fence for the first write of the header fields.
- [ ] 14f2411 [C++]:  Disable bounds checks for release builds of media driver.
- [ ] 4e014cf [C++]: add thread_fence() after volatile write of negative frame length.
- [ ] 714113a [Java] Use arrays rather than ArrayLists for positions in publications and images in the driver.
- [ ] 41a18e1 Merge remote-tracking branch 'origin/master'
- [ ] 0879627 [Java] Upgrade to ByteBuddy 1.4.7.
- [ ] 875f7bb [Java] Upgrade to ByteBuddy 1.4.8.
- [ ] 3733f6c [Java] Move tail counters into log meta data for the Publication which allows for simplification of the log structure and reduce data dependant loads throughout Aeron.
- [ ] 99ebefd [Java] Place the active partition index in the same cache line as the tail counters within the log.
- [ ] f704681 [C++]: reflect tail counters being moved into log meta data buffer.
- [ ] 18ec519 [C++]: add spins on CnC file to Aeron constructor.
- [ ] c54f276 [Java] Javadoc correction.
- [ ] dee27a0 Merge remote-tracking branch 'origin/master'
- [ ] b8d83be [Java] Give up the thread on an setup thread which is adding publications or subscriptions to that CPU resource is available to other threads to complete the action. Issue #244.
- [ ] 8815092 [Java] Naming.
- [ ] 3352811 [Java] Incremental cleaning of log buffers by the conductor to smooth out pauses in the driver conductor.
- [ ] 5800f5f [Java] Lag the cleaning by a term + window to allow for greater NAK range.
- [ ] b7a0be3 [Java] Naming of cleaning variables for clarity.
- [ ] b882e71 [Java] Check resend of a NAK is within one term length behind the sender position. Also clean incrementally from 2 term lengths behind publication limit for the NetworkPublication. Issue #257.
- [ ] 21c27b0 [Java] Naming.
- [ ] 3d060f1 [Java] Naming.
- [ ] d6eec29 [Java] README.
- [ ] 32504cb [Java] README.
- [ ] 6f2d1f1 [Java]: avoid issuing availableImage on addSubscription when existing image status isn't ACTIVE.
- [ ] bbaf75d [Java]: switch filtering of addImage for availableImage to be correlationId based instead of sessionId.
- [ ] bb6f682 [C++]: make hasImage be correlationId based.
- [ ] 6d3d702 [Java] naming.
- [ ] 34d53ea Merge branch 'master' of https://github.com/real-logic/Aeron
- [ ] 023d9e2 [Java] Use concrete typed position counters in status package.
- [ ] 80c5710 [C++] Added setting clientId on remove messages to the driver
- [ ] f07738b [Java] Simplify DriverProxy as it is only called on the conductor lock and benefit from the clientId field set in the buffer.
- [ ] 2808ab8 [Java] Simplify DriverProxy as it is only called under the client conductor lock and benefit from the clientId field set in the buffer.
- [ ] d1a76af Merge pull request #259 from lirm/master
- [ ] 27ade16 [Java] Styling.
- [ ] 677399a [Java] Upgrade to ByteBuddy 1.4.9.
- [ ] 957e552 [Java] Upgrade to Checkstyle 7.0.
- [ ] d31a838 [Java] Styling.
- [ ] 375b625 [Java] Exposed max payload length from a publication.
- [ ] c2e5378 [C++]: add maxPayloadLength to Publication
- [ ] 7b21578 1.0 released
- [ ] a57bdf5 post release bump
- [ ] 5a11d6e [Java] Update to ByteBuddy 1.4.15.
- [ ] 84d1433 [Java] Simplify agent thread creation.
- [ ] 98b8759 Support passing ThreadFactory instances to the Aeron.Context to use when constructing the conductor thread.
- [ ] fff6dbf Merge pull request #261 from mikeb01/master
- [ ] bff0c8d [Java] Styling.
- [ ] 57edbb2 [c++]: Fix OneToOneConcurrentArrayQueue.
- [ ] b091cd7 [C++]: fix driver build.
- [ ] 6b053d9 [C++]: add more of a test for OneToOneConcurrentArrayQueue
- [ ] d37a87f add some clarifying statements on C++ driver status
- [ ] 396c172 [C++]: add memory include
- [ ] a60280b Update README.md
